var user_database_js = [
	{
		name: 'Marcos',
		passw: '42',
		email: 'mrbjr@outlook.com',
		prof: 'default',
		bg: '2',
	},
	{
		name: 'Visitante',
		passw: 'guest',
		email: 'guest@br.com',
		prof: 'default',
		bg: '3',
	},
	{
		name: 'Matheus',
		passw: 'guest',
		email: 'matheusvb2@gmail.com',
		prof: 'default',
		bg: '3',
	  },
	  {
		name: 'Visitante Livre',
		passw: '',
		email: 'visitante',
		prof: '',
		bg: '3',
		}
  ]

  var materials = [
	{
		categ: 'heavy',
		name: 'Concreto',
		brand: 'ISO 12354-1:2017',
		density: 2200,
		ym: undefined,
		pm: undefined,
		wave: 3800,
		loss: 0.005,
		ide: 1,
	},
	{
		categ: 'float',
		name: 'Piso flutuante genérico (s=8)',
		brand: 'ISO 12354-1:2017',
		density: 2100,
		ym: 8,
		tp: 'sand', //sand ou asphalt
		ide: 2,
	},
	{
		categ: 'heavy',
		name: 'Calcium-silicate blocks',
		brand: 'ISO 12354-1:2017',
		density: 1800,
		ym: undefined,
		pm: undefined,
		wave: 2500,
		loss: 0.01,
		ide: 3,
	},
	{
		categ: 'heavy',
		name: 'Autoclaved aerated concrete blocks',
		brand: 'ISO 12354-1:2017',
		density: 800,
		ym: undefined,
		pm: undefined,
		wave: 1900,
		loss: 0.0125,
		ide: 4,
	},
	{
		categ: 'heavy',
		name: 'Lightweight aggregate blocks',
		brand: 'ISO 12354-1:2017',
		density: 1400,
		ym: undefined,
		pm: undefined,
		wave: 2200,
		loss: 0.01,
		ide: 5,
	},
	{
		categ: 'heavy',
		name: 'Dense aggregate blocks',
		brand: 'ISO 12354-1:2017',
		density: 2000,
		ym: undefined,
		pm: undefined,
		wave: 2700,
		loss: 0.01,
		ide: 6,
	},
	{
		categ: 'heavy',
		name: 'Bricks',
		brand: 'ISO 12354-1:2017',
		density: 2000,
		ym: undefined,
		pm: undefined,
		wave: 2700,
		loss: 0.01,
		ide: 7,
	},
	{
		categ: 'heavy',
		name: 'Plasteboard (natural gypsum)',
		brand: 'ISO 12354-1:2017',
		density: 860,
		ym: undefined,
		pm: undefined,
		wave: 1490,
		loss: 0.0141,
		ide: 8,
	},
	{
		categ: 'heavy',
		name: 'Plasteboard (flue gas and natural gypsum)',
		brand: 'ISO 12354-1:2017',
		density: 680,
		ym: undefined,
		pm: undefined,
		wave: 1810,
		loss: 0.0125,
		ide: 9,
	},
	{
		categ: 'heavy',
		name: 'Chipboard',
		brand: 'ISO 12354-1:2017',
		density: 760,
		ym: undefined,
		pm: undefined,
		wave: 2200,
		loss: 0.01,
		ide: 10,
	},
	{
		categ: 'heavy',
		name: 'Bloco de concreto',
		brand: 'ISO 12354-1:2017',
		density: 600,
		ym: undefined,
		pm: undefined,
		wave: 1900,
		loss: 0.0125,
		ide: 11,
	},
	{
		categ: 'float',
		name: 'Piso Zero',
		brand: 'zero',
		density: 0,
		ym: 0,
		tp: 'sand', //sand ou asphalt
		ide: 12,
	},
  ]

export default {user_database_js,materials}; 